### ISSUE TITLE
[질문] 사용자가 카카오 로그인을 했을 때, JWT 전달을 쿠키로 해도 될까요?

### ISSUE THREAD

**Issue by juyohan** [fantasy-fans-ko/lad-be#19]
1. JWT를 헤더가 아닌 쿠키로 전송하는건 어떠할까요? (처음 로그인에 한 함.)
2. JWT를 쿠키로 전송하는 김에, 사용자의 정보 (id, kakao_image_path) 등을 json 형식으로 같이 감싸서 보내도 될까요?

<hr>

### 1번의 이유있는 이유
현재 카카오 로그인을 Spring boot 에서 제공해주는 `OAuth2 Client 프레임워크` 를 사용을 합니다. 그래서 로그인을 성공했을 때, `JWT` 를 생성하고 Header 에 추가하여 Redirect를 하였습니다. 하지만 `Redirect` 는 새로운 response와 request의 생성으로 인해 전에 추가한 JWT를 넣은 Header는 넘어가지 않습니다.

### Redirect가 되기 전, 응답과 요청

<img width="506" alt="스크린샷 2021-12-14 오후 9 12 22" src="https://user-images.githubusercontent.com/20573091/145996094-14cc9d39-e5dd-4912-a926-af27b554c268.png">

### 지정해둔 경로로 Redirect가 되고 난 후, 요청 (응답 x)

<img width="506" alt="스크린샷 2021-12-14 오후 9 12 30" src="https://user-images.githubusercontent.com/20573091/145996112-ce91bd04-486e-4cef-9c66-ea67b3f8a62b.png">

위와 같은 상황으로 JWT 를 `쿠키` 에 담아 전송을 하려고 합니다.

<hr>

### 2번의 제안
JWT를 쿠키에 담아 전송을 하는김에 유저의 정보도 같이 Json 형식으로 감싸서 보내려고 하는데 어떠한가요?

<hr>

### 결론
JWT, 사용자의 정보를 쿠키에 Json 형식으로 감싸서 보내주려고 합니다.
혹시, 다른 좋은 방법이나 생각이 있으시다면 공유 부탁드립니다.

# 캄샤함니다.

**Comment by philipjkim** [comment]
@juyohan 
제가 상황을 정확히 이해한건지는 잘 모르겠으나 모든 인증 과정이 끝났고 우리쪽 b/e 에서 JWT 를 응답헤더 혹은 바디로 f/e 쪽에 전달했다면, f/e 쪽에서는 받은 JWT 를 local storage 에 저장해두고 이후 b/e api 호출시 해당 JWT 를 요청헤더에 실어서 보내면 되는것 아닌가요?

**Comment by juyohan** [comment]
b/e 에서는 페이지 이동을 직접 하는게 아니라, 여러가지 정보 (페이지 이동에 대한 정보나 사용자의 정보, JWT 등등) 를 f/e 쪽에 알려주는 방식으로 해야한다.

**Comment by juyohan** [comment]
> b/e 에서는 페이지 이동을 직접 하는게 아니라, 여러가지 정보 (페이지 이동에 대한 정보나 사용자의 정보, JWT 등등) 를 f/e 쪽에 알려주는 방식으로 해야한다.

해당 이슈는 위의 내용으로 해결이 되었기에 닫습니다.
