### ISSUE TITLE
DB 스키마 설계

### ISSUE THREAD

**Issue by philipjkim** [fantasy-fans-ko/lad-be#2]
먼저 https://github.com/fantasy-fans-ko/lad-fe/issues/2 이슈가 해결되고 나면, 초기 스펙 기준으로 DB 스키마를 잡아봅니다.

**Comment by philipjkim** [comment]
@juyohan @kimdg1105 어제 밤 미팅내용을 따로 이슈를 생성해서 정리해주셨는데, 그 내용 중 DB 관련된 내용들은 중복되더라도 이 이슈에 계속 커멘트로 히스토리 남겨주세요~

**Comment by juyohan** [comment]
https://github.com/fantasy-fans-ko/lad-be/issues/6#issue-1043831193

11 / 3
DB 스키마 초안

**Comment by philipjkim** [comment]
대부분의 스키마 관련 논의가 https://github.com/fantasy-fans-ko/lad-be/issues/6 에서 이루어지므로 이 이슈는 종료시킵니다.
