### ISSUE TITLE
[FEATURE] init setting

### ISSUE THREAD

**Issue by juyohan** [fantasy-fans-ko/lad-be#9]
## Description

프로젝트의 초기 셋팅을 합니다.

## Branch

feature/init-setting

## Progress

- [x] DB 설정 및 연결
- [x] Entity 생성
- [x] 의존성 추가

**Comment by philipjkim** [comment]
@juyohan 이미 새로 만든 이슈와 중복되는 기존 이슈 https://github.com/fantasy-fans-ko/lad-be/issues/1 가 있습니다. 앞으론 이슈를 생성하기 전에 기존 이슈 중 이미 내가 만들려고 하는 것이 있는지 보고, 있다면 그 이슈에 본인을  assign 하고 이슈를 진행해 나가시면 됩니다. 요런건 자꾸 습관을 들여야해요 (나 말고 다른 동료가 어떤 이슈를 어떤 목적으로 만들었는지에 대한 관심을 갖기) 일단 1번 이슈는 제가 중복으로 처리하고 삭제할게요.
